version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      PROFILE: docker
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_CONTAINER_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: taxi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
