spring:
  flyway:
    url: jdbc:postgresql://${MIGRATION_DATABASE_HOST}:${MIGRATION_DATABASE_PORT}/${MIGRATION_DATABASE_NAME}
    user: ${MIGRATION_DATABASE_USER}
    password: ${MIGRATION_DATABASE_PASSWORD}
    schemas: live
    locations: classpath:db/migration
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

server:
  port: ${RUNNING_PORT}
