spring:
  flyway:
    url: ${DB_TEST_URL}
    user: ${DB_TEST_USER}
    password: ${DB_TEST_PASSWORD}
    schemas: live
    locations: [classpath:db/migration, classpath:db/integration-test-migration]
  datasource:
    url: ${DB_TEST_URL}
    username: ${DB_TEST_USER}
    password: ${DB_TEST_PASSWORD}
    driver-class-name: org.postgresql.Driver
